### ISSUE TITLE
Entimport Roadmap

### ISSUE THREAD

**Issue by zeevmoney** [ariga/entimport#27]
Current roadmap for `entimport`.  
This is an open discussions, the list may be changed.  
Contributions to the task content and task themselves are welcome.

- [ ] Add support for special types: 
  - [ ] JSON
  - [ ] postgres.NetworkType
  - [ ] postgres.BitType
  - [ ] SpatialType
  - [ ] postgres.CurrencyType 
  - [ ] postgres.XMLType
  - [ ] postgres.ArrayType
  - [ ] postgres.UserDefinedType
  - [ ] UUID.
- [ ] Add support for non go driver MySQL DSNs in the mux.
- [ ] Index support (currently Unique index is supported).
- [ ] Support for editing schema both manually and automatically (real upsert and not only overwrite)
- [ ] Export API
- [ ] Add indentations (pretty print)

**Comment by thmeitz** [comment]
please add mysql.Set type 
see #28

**Comment by zeevmoney** [comment]
> please add mysql.Set type see #28
> 
> * https://dev.mysql.com/doc/refman/8.0/en/set.html
> * https://mariadb.com/kb/en/set-data-type/

Hi @thmeitz, thanks for reaching out!
I will prioritize it, this can be done using field "string" and ent `SchemaType`, requires some work in [contrib/schemast](https://github.com/ent/contrib) and in this repo of course.
